# ==============================================================================
# Tools

proto_update:
	buf mod update ./pkg/network

proto_gen:
	buf generate ./pkg/network

proto_lint:
	buf lint ./pkg/network